name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to server REMOTE_HOST ${{ secrets.SSH_HOST }} REMOTE_USER ${{ secrets.SSH_USERNAME }} SSH_PRIVATE_KEY ${{ secrets.SSH_KEY }}
        run:
          ssh -i "StarMatch.pem" ec2-user@ec2-13-37-220-62.eu-west-3.compute.amazonaws.com
          cd ${{ env.TARGET_DIR }}
          rm -rf *
          scp -r ${{ env.PROJECT_ROOT_DIR }}/build/* ${{ env.TARGET_DIR }}
      - name: sleep
        run: sleep 30000 & 1
env:
  # Replace with your actual secrets
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  TARGET_DIR: /var/www/html
  PROJECT_ROOT_DIR: front
