name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install nvm
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
        shell: bash
      - name: Install Node.js
        run: |
          nvm install 16
      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.1.4
        with:
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SOURCE: "build"
          TARGET: "/var/www/html"

env:
  # Replace with your actual secrets
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
